spring:
  datasource:
<<<<<<< HEAD
    url:jdbc:mysql://localhost:3306/company_db?useSSL=false&serverTimezone=UTC
=======
    url:jdbc:mysql://localhost:3306/company_db?
>>>>>>> 16c6dac (code1)
    username:root
    password:root
